ekf_filter:
  ros__parameters:
    frequency:            30.0      
    sensor_timeout:       0.5
    two_d_mode:           true

    base_link_frame:      base_link
    odom_frame:           odom
    world_frame:          odom        

    odom0:                /odom
    odom0_differential:   true       
    odom0_relative:       false
    odom0_config:         [true, true, false,
                           false, false, true,
                           true,  true,  false,
                           false, false, true,
                           false, false, false]
    imu0:                 /imu
    imu0_nodelay:         true
    imu0_differential:    false
    imu0_relative:        false
    imu0_config:          [false, false, false,
                           false, false, false,
                           false, false, false,
                           true,  true,  true,
                           true,  true,  true]
    imu0_linear_acceleration_rejection_threshold: 0.8
    imu0_angular_velocity_rejection_threshold:    0.8

    publish_tf:           true
