slam_toolbox:
  ros__parameters:
    mode: "mapping"
    map_update_interval: 1.0       
    map_resolution: 0.05          
    map_frame: map
    queue_size: 20 
    odom_frame: odom
    base_frame: base_link
    provide_odom_frame: true
    use_scan_matching: true
    num_particles: 30
    scan_topic: scan
    transform_publish_period: 0.05
    tf_buffer_duration: 10.0
    transform_timeout: 0.3